### ISSUE TITLE
write_geomarker_file argument default using env vars?

### ISSUE THREAD

**Issue by erikarasnick** [degauss-org/dht#66]
https://github.com/degauss-org/dht/blob/959e1c96b0526b8bfa05c549fc05bf919a1c3c29/R/write_geomarker_file.R#L26

Can we make this `argument = Sys.getenv("degauss_argument")` ? Would that be a problem if it doesn't exist?

**Comment by cole-brokamp** [comment]
The "degauss_argument" env var is really more meant to be informative to the user than really defining the value used.  for example, for the geocode container it is `valid_geocode_score_threshold [default: 0.5]`.  When using it inside the geocoder container, we might want to append `threshold_0.3` (for example, if a user calls with the argument 0.3) instead of the above message.

this is the same with the drivetime container; we want to append the provided argument value, not the argument description

**Comment by erikarasnick** [comment]
oh, okay, that makes sense

**Comment by cole-brokamp** [comment]
I did think about using it that way initially, but looking at our specific situations where we need arguments made me realize that there probably is no good way to generalize that and will require application-specific code to put the argument value in the output file name.
