### ISSUE TITLE
degauss_run potential issues

### ISSUE THREAD

**Issue by qing-duan** [degauss-org/dht#86]
- An issue with duplicated addresses: using dplyr::left_join results in more rows than expected.
- An issue with identifying the saved output file: *list.files(dirname(tf), pattern = tools::file_path_sans_ext(basename(tf)), full.names = TRUE)[1]*. *list.files()[1]* pick the 1st file listed but somehow my output file is listed as the 2nd, which can't be read in correctly. Maybe consider using the actual file name: *list.files(dirname(tf), pattern = **paste(tools::file_path_sans_ext(basename(tf)), image, version, sep="_")**, full.names = TRUE)*. That worked for me.
- May consider having degauss_run clean up the generated temporary input and output files at the end.

**Comment by cole-brokamp** [comment]
Thanks!  To address each one

- agreed that this is an issue and I will work to fix this problem where input files with duplicated addresses return more rows than expected
- This one is tough because this pattern for names won't be the same if someone calls with an argument or without a version number.  But I agree that using the first file is not ideal.  Sounds like a platform difference on how the files are listed and I need something more specific.
- These files are stored in the platform-specific temporary directory and are cleaned every time R is restarted, so no cleanup from our end should be necessary.

My TODOs on updating degauss_run are:

- [ ] make sure that it works with no version specified
- [ ] make sure it works okay with and without argument
- [ ] make better way to specify output file name (using hash instead of temporary file name)?
- [ ] use `.row` instead of address to merge in output

**Comment by cole-brokamp** [comment]
I think all of these are fixed in #87.  @qing-duan -- are you running this on Windows?
